### ISSUE TITLE
Expand KeyStoreDsl to store data 

### ISSUE THREAD

**Issue by AlahmadiQ8** [bcgit/bc-kotlin#10]
Hi, 

Thank you for this awesome library. I love the idiomatic kotlin style. 

Recently watched https://www.youtube.com/watch?v=W9bR014L2SQ and it's been incredibly helpful and how i stumbled on bc-kotlin. 

_Disclosure: i'm not an expert in crypto but we use BC libraries for basic crypto operations at work written in Kotlin. So forgive me for the information gap._

I've been trying to convert our BC libraries to use this  as an experiment and noticed some limitations for my use cases. 

Here are the following use cases: 

## Ability to create keyStore

right now keyStore builder is not exposed and I have to add the following extension myself as follows: 

```kotlin
fun keyStore(block: KeyStoreBuilder.() -> Unit) = KeyStoreBuilder().apply(block).build()
```

It would be great if it's exposed. 

## Dsl for storing private keys and certificates in key store

Something like this maybe? this is my humble messy attempt 

```kotlin

// DSL
keyStore.save {
    fileName = "test.p12"
    storePassword = "password"
    alias = "test"
    certificate = createSelfSignedCertificate(kp)
    privateKey = kp.private
}

// --------
// Implementation 

class StoreActionBuilder {
    lateinit var fileName: String
    lateinit var storePassword: String
    lateinit var alias: String
    var privateKey: java.security.PrivateKey? = null
    var keyPassword: String = ""
    var certificate: Certificate? = null

    fun store(keyStore: KeyStore) {
        if (privateKey != null && certificate != null) {
            keyStore.setKeyEntry(alias, privateKey,  keyPassword.toCharArray(),  arrayOf(certificate!!.toX509Certificate()))
        } else if (privateKey == null && certificate != null) {
            keyStore.setCertificateEntry(alias, certificate!!.toX509Certificate())
        } else if (privateKey != null) {
            keyStore.setKeyEntry(alias, privateKey,  keyPassword.toCharArray(),  emptyArray())
        } else {
            throw IllegalArgumentException("certificate and privateKey cannot be both null")
        }

        keyStore.save(fileName, storePassword)
    }
}

fun KeyStore.save(builder: StoreActionBuilder.() -> Unit) {
    StoreActionBuilder().apply(builder).store(this)
}

fun KeyStore.save(fileName: String, password: String) {
    FileOutputStream(fileName).use {
        store(it, password.toCharArray())
    }
}
```

## `X509Certificate` in `Certificate` carrier class

While testing, a lot of our operations requires working with `X509Certificate`. However, `Certificate` doesn't expose is since `_cert` holder is internal. 

It would be great if we can expose `X509CertificateHolder` so we can add our own extension methods to get `X509Certificate`. 

**Example:**
When I need to store certificates into keyStore, `setCertificateEntry` expects a `X509Certificate` input argument.

## export `java.security.PrivateKey` and `java.security.PublicKey` in `signingKeyPair` and `encryptionKeyPair`

Similarly, I'd need `java.security.PrivateKey`  exposed since `KeyStore.setKeyEntry` expects `java.security.PrivateKey`

**Comment by dghgit** [comment]
Thanks for the feedback, I'll look into it and get back.

**Comment by dghgit** [comment]
I have a bit of a look at this. Would this issue be better dealt with if I added some DSL to support adding of entries to keystores and did the conversions to the base java types internally?

If I understand correctly there's still a need to add support for getting X509 certificate as well, but I'm expecting resolving the above will show the right way to resolve this as well.

**Comment by AlahmadiQ8** [comment]
@dghgit  apologies for the late response. 

You care correct on the first point. Although it would be nice to have to have the option to get the internal X509 certificate as well.

**Comment by AlahmadiQ8** [comment]
I built my own dsl for now for keystore.


```kotlin
class KeyStoreDslTests : FunSpec({
    beforeSpec {
        using(findBCProvider())
    }

    test("should work") {
        val file = tempfile(suffix = ".pfx")
        val filePath = file.absolutePath
        println(filePath)

        val kp = keyPair {
            rsa {
                keySize = 2048
            }
        }

        val keyStore = keyStore {
            storeName = ""
            storePassword = "password".toCharArray()
            storeType = "pkcs12"
        }

        keyStore.save {
            storeName = filePath
            storePassword = "password"
            alias = "test"
            certificate = createSelfSignedCertificate()
            privateKey = kp.private
            keyPassword = ""
        }

        val privateKey = privateKeyFromStore {
            this.keyStore = keyStore
            alias = "test"
            keyPassword = "".toCharArray()
        }

        privateKey.encoded shouldBe kp.private.encoded
    }
})
```

**Comment by dghgit** [comment]
Hi, I've finally submitted something on this - it just supports PKCS12 at the moment. I'll add BCFKS next. The password requirements for the two keystore types are quite different, it seemed like a better idea to separate them because of this. See MakeKeyStore.kt in the examples for usage.

**Comment by AlahmadiQ8** [comment]
Thank you so much! I checked the example and looks great :)
